title: studioplietsch
default_lang: de
author:
  name: 'Clara Zachariassen'
  email: info@studioplietsch.de
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
